#ifndef QTDATASYNCANDROID_GLOBAL_H
#define QTDATASYNCANDROID_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef QT_STATIC
#  if defined(QT_BUILD_DATASYNCANDROID_LIB)
#    define Q_DATASYNCANDROID_EXPORT Q_DECL_EXPORT
#  else
#    define Q_DATASYNCANDROID_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_DATASYNCANDROID_EXPORT
#endif

#endif // QTDATASYNCANDROID_GLOBAL_H
